apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitris-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitris-backend
  template:
    metadata:
      labels:
        app: gitris-backend
    spec:
      serviceAccountName: gitris-backend-sa
      containers:
      - name: gitris-backend-container
        # ECRのURIに置換
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/gitris-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: gitris-backend-secrets
        env:
        - name: AWS_DEFAULT_REGION
          value: "ap-northeast-1"
        - name: CORS_ALLOWED_ORIGINS
          value: "http://aedcc17e393d341c483d9391c3b953ef-1271805315.ap-northeast-1.elb.amazonaws.com"
---
apiVersion: v1
kind: Service
metadata:
  name: gitris-backend-service
spec:
  type: LoadBalancer
  selector:
    app: gitris-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitris-backend-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: gitris-backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: gitris/jwt-secret
        property: secret
    - secretKey: DB_USERNAME
      remoteRef:
        key: gitris/database
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: gitris/database
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: gitris/database
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: gitris/database
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: gitris/database
        property: dbname
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: gitris/github-oauth
        property: client_id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: gitris/github-oauth
        property: client_secret
