apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitris-backend-sa
  namespace: default
  annotations:
    #　デプロイの際に IRSA 用の IAM ロール ARN に置換
    eks.amazonaws.com/role-arn: "arn:aws:iam::678780125373:role/gitris-backend-irsa-role"
